variables:
  PROJECT_MODULES: "account_fiscal_period,account_fiscal_year,date_range,kzm_edi_simplir,kzm_payroll_ma,kzm_payroll_ma_reports,partner_extend,kzm_edi_cimr,kzm_edi_damancom"
  ODOO_VERSION: "12.0"
  CI_BUILD_REF: "gitlab_database"

stages:
  - build

tests:
  stage: build
  script:
  - dropdb --if-exists $CI_BUILD_REF
  - virtualenv env
  - source env/bin/activate
  - git clone --quiet --depth=1 --branch=$ODOO_VERSION https://github.com/odoo/odoo.git env/odoo
  - git clone --quiet --depth=1 --branch=master http://r.rouichi:1kzmreda1@gitlab.karizma-conseil.com/root/kzm_accounting.git  env/kzm/kzm_accounting
  - rm -rf env/odoo/.git
  - pip3 install -r env/kzm/requirements.txt
  - createdb --encoding=UTF8 --locale=en_US.UTF-8 --template=template0 $CI_BUILD_REF
  - ./env/odoo/odoo-bin -d $CI_BUILD_REF --addons-path=./env/odoo/addons/,./env/kzm/kzm_accounting/,./ --log-level=warn --stop-after-init
  - ./env/odoo/odoo-bin -d $CI_BUILD_REF --addons-path=./env/odoo/addons/,./env/kzm/kzm_accounting/,./ -i $PROJECT_MODULES --without-demo=all --log-level=warn --stop-after-init
  - ./env/odoo/odoo-bin -d $CI_BUILD_REF --addons-path=./env/odoo/addons/,./env/kzm/kzm_accounting/,./ -i $PROJECT_MODULES --test-enable --log-level=warn --stop-after-init
  - dropdb --if-exists $CI_BUILD_REF
