variables:
  EXTRA_MODULES: ""
  ODOO_VERSION: "13.0"
  CI_BUILD_REF: "gitlab_database"

stages:
  - build

tests:
  stage: build
  script:
  - dropdb --if-exists $CI_BUILD_REF
  - python3 -m venv env
  - source env/bin/activate
  - PROJECT_MODULES=$(ls -m ./ | tr -d '\n')
  - git clone --quiet --depth=1 --branch=$ODOO_VERSION https://github.com/odoo/odoo.git env/odoo
  - git clone --quiet --depth=1 --branch=$ODOO_VERSION git@51.83.109.211:root/kzm_accounting.git env/kzm/kzm_accounting
  - git clone --quiet --depth=1 --branch=$ODOO_VERSION https://github.com/OCA/server-ux.git env/oca/server-ux
  - rm -rf env/odoo/.git
  - pip3 install -r ./env/odoo/requirements.txt
  - createdb --encoding=UTF8 --locale=en_US.UTF-8 --template=template0 $CI_BUILD_REF
  - ./env/odoo/odoo-bin -d $CI_BUILD_REF --addons-path=./env/odoo/addons/,./env/kzm/kzm_accounting/,./,./env/oca/server-ux --log-level=warn --stop-after-init
  - ./env/odoo/odoo-bin -d $CI_BUILD_REF --addons-path=./env/odoo/addons/,./env/kzm/kzm_accounting/,./,./env/oca/server-ux -i "${PROJECT_MODULES//[[:blank:]]/}" --without-demo=all --log-level=warn --stop-after-init
  - ./env/odoo/odoo-bin -d $CI_BUILD_REF --addons-path=./env/odoo/addons/,./env/kzm/kzm_accounting/,./,./env/oca/server-ux -i "${PROJECT_MODULES//[[:blank:]]/}" --test-enable --log-level=warn --stop-after-init
  - rm -rf ./env/odoo-enterprise ./env/odoo ./env/oca ./env/kzm 
  - dropdb --if-exists $CI_BUILD_REF
