variables:
  PROJECT_MODULES: "account_fiscal_period,account_fiscal_year,date_range,etat_9421,hr_payroll_ma,hr_payroll_ma_legal_reports,partner_extend,teledeclaration_cimr,teledeclaration_cnss"
  ODOO_VERSION: "11.0"

stages:
  - build

tests:
  stage: build
  script:
  - dropdb --if-exists "gitlab-runner"
  - virtualenv env
  - source env/bin/activate
  - pip install -r requirements.txt
  - git clone --quiet --depth=1 --branch=$ODOO_VERSION https://github.com/odoo/odoo.git env/odoo
  - rm -rf env/odoo/.git
  - UPDATE pg_database SET datistemplate = FALSE WHERE datname = 'template1';
  - DROP DATABASE template1;
  - CREATE DATABASE template1 WITH TEMPLATE = template0 ENCODING = 'UNICODE';
  - UPDATE pg_database SET datistemplate = TRUE WHERE datname = 'template1';
  - createdb --encoding=UTF8 --locale=en_US.UTF-8 --template=template1
  - ./env/odoo/odoo-bin -d $CI_BUILD_REF --addons-path=./env/odoo/addons/,./ --log-level=warn --stop-after-init
  - ./env/odoo/odoo-bin -d $CI_BUILD_REF --addons-path=./env/odoo/addons/,./ -i $PROJECT_MODULES --without-demo=all --log-level=warn --stop-after-init
  - ./env/odoo/odoo-bin -d $CI_BUILD_REF --addons-path=./env/odoo/addons/,./ -i $PROJECT_MODULES --test-enable --log-level=warn --stop-after-init
  - dropdb --if-exists $CI_BUILD_REF
